# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-30 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20171130_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerform',
            old_name='full_name',
            new_name='full_Name',
        ),
        migrations.RenameField(
            model_name='registerform',
            old_name='phone_number',
            new_name='phone_Number',
        ),
        migrations.RenameField(
            model_name='registerform',
            old_name='comment',
            new_name='question',
        ),
    ]
